spring:
  application:
    name: bankingsystem

  datasource:
    url: jdbc:mysql://localhost:3306/digitalBanking
    username: root
    password: qwerty123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    root: INFO
    com.yourpackage: DEBUG

#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

  file:
    name: logs/bankingsystem.log

management:
  endpoints:
    web:
      exposure:
        include: "*"